# SearXNG settings - Generated by Terraform from variables
# Customized from official SearXNG defaults for homelab deployment

server:
  port: 8080
  bind_address: "0.0.0.0"
  secret_key: "searxng-secret-key-change-in-production"
  base_url: false
  image_proxy: false
  method: "POST"
  default_http_headers:
    X-Content-Type-Options: nosniff
    X-Robots-Tag: "noindex, nofollow"
    Referrer-Policy: "no-referrer"
  # Disable bot detection for homelab use (no reverse proxy to provide X-Forwarded-For)
  limiter: false
  # Direct access from Zeropoint network - use socket peer address
  public_instance: false
  trusted_proxies: []

ui:
  static_path: ""
  templates_path: ""
  default_theme: "simple"
  center_alignment: false
  default_locale: ""
  query_in_title: false
  theme_args:
    simple_style: "auto"
  search_on_category_select: true
  hotkeys: default
  url_formatting: pretty

search:
  safe_search: ${safe_search}
  autocomplete: "${autocomplete}"
  autocomplete_min: 4
  default_lang: ""
  ban_time_on_fail: 5
  max_ban_time_on_fail: 120
  suspended_times:
    SearxEngineAccessDenied: 86400
    SearxEngineCaptcha: 86400
    SearxEngineTooManyRequests: 3600
    cf_SearxEngineCaptcha: 1296000
    cf_SearxEngineAccessDenied: 86400
    recaptcha_SearxEngineCaptcha: 604800
  formats:
    - html
    - json
    - rss

outgoing:
  request_timeout: ${request_timeout}
  enable_http2: true
  pool_connections: 100
  pool_maxsize: 20

general:
  debug: false
  instance_name: "${instance_name}"
  privacypolicy_url: false
  donation_url: false
  contact_url: false
  enable_metrics: true
  open_metrics: ""

brand:
  new_issue_url: "https://github.com/searxng/searxng/issues/new"
  docs_url: "https://docs.searxng.org/"
  public_instances: "https://searx.space"
  wiki_url: "https://github.com/searxng/searxng/wiki"
  issue_url: "https://github.com/searxng/searxng/issues"

doi_resolvers:
  oadoi.org: 'https://oadoi.org/'
  doi.org: 'https://doi.org/'
  sci-hub.se: 'https://sci-hub.se/'
  sci-hub.st: 'https://sci-hub.st/'
  sci-hub.ru: 'https://sci-hub.ru/'

default_doi_resolver: 'oadoi.org'

locales:
  en: English
  de: Deutsch
  fr: Français
  es: Español
  it: Italiano
  ja: 日本語
  nl: Nederlands
  pt-BR: Português (Brasil)
  pt-PT: Português (Portugal)
  ru: Русский
  tr: Türkçe
  zh: 中文

valkey:
  url: false

plugins:
  searx.plugins.calculator.SXNGPlugin:
    active: true
  searx.plugins.infinite_scroll.SXNGPlugin:
    active: false
  searx.plugins.hash_plugin.SXNGPlugin:
    active: true
  searx.plugins.self_info.SXNGPlugin:
    active: true
  searx.plugins.unit_converter.SXNGPlugin:
    active: true
  searx.plugins.ahmia_filter.SXNGPlugin:
    active: true
  searx.plugins.hostnames.SXNGPlugin:
    active: true
  searx.plugins.time_zone.SXNGPlugin:
    active: true
  searx.plugins.oa_doi_rewrite.SXNGPlugin:
    active: false
  searx.plugins.tor_check.SXNGPlugin:
    active: false
  searx.plugins.tracker_url_remover.SXNGPlugin:
    active: true

checker:
  off_when_debug: true

categories_as_tabs:
  general:
  images:
  videos:
  news:
  map:
  music:
  it:
  science:
  files:
  social media:

engines:
  - name: duckduckgo
    engine: duckduckgo
    shortcut: ddg

  - name: google
    engine: google
    shortcut: go

  - name: wikipedia
    engine: wikipedia
    shortcut: wp
    display_type: ["infobox"]
    categories: [general]

  - name: wiktionary
    engine: mediawiki
    shortcut: wt
    categories: [dictionaries, wikimedia]
    base_url: "https://{language}.wiktionary.org/"
    search_type: text

  - name: startpage
    engine: startpage
    shortcut: sp
    startpage_categ: web
    categories: [general, web]

  - name: bing
    engine: bing
    shortcut: bi
    disabled: true

